// This is an autogenerated file from running `firebase genkit:flow`.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for suggesting habits based on user goals.
 *
 * - suggestHabits - A function that takes user goals as input and returns habit suggestions.
 * - SuggestHabitsInput - The input type for the suggestHabits function.
 * - SuggestHabitsOutput - The return type for the suggestHabits function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestHabitsInputSchema = z.object({
  goals: z
    .string()
    .describe("The user's health and life goals, which will be used to generate habit suggestions."),
});
export type SuggestHabitsInput = z.infer<typeof SuggestHabitsInputSchema>;

const SuggestHabitsOutputSchema = z.object({
  habits: z.array(z.string()).describe('An array of habit suggestions.'),
});
export type SuggestHabitsOutput = z.infer<typeof SuggestHabitsOutputSchema>;

export async function suggestHabits(input: SuggestHabitsInput): Promise<SuggestHabitsOutput> {
  return suggestHabitsFlow(input);
}

const suggestHabitsPrompt = ai.definePrompt({
  name: 'suggestHabitsPrompt',
  input: {schema: SuggestHabitsInputSchema},
  output: {schema: SuggestHabitsOutputSchema},
  prompt: `You are a helpful assistant that suggests habits based on user goals.

  The habits should be specific and actionable.

  User Goals: {{{goals}}}

  Suggest habits:
  `,
});

const suggestHabitsFlow = ai.defineFlow(
  {
    name: 'suggestHabitsFlow',
    inputSchema: SuggestHabitsInputSchema,
    outputSchema: SuggestHabitsOutputSchema,
  },
  async input => {
    const {output} = await suggestHabitsPrompt(input);
    return output!;
  }
);
